### ISSUE TITLE
lnp-node address not have regtest prefix 'bcrt'

### ISSUE THREAD

**Issue by crisdut** [LNP-WG/lnp-node#48]
**Classify the bug**
- [x] Incorrect results

**Describe the problem**
The 'lnp-node' return the testnet prefix ('tb') instead of regtest prefix ('bcrt').

**To Reproduce**
1. Initialize 'lnpd' with '--chain=regtest' argument
2. Set your master xpriv (Ex: tprv9s21Z....vSexk)
3. Running 'lnpd' with '--chain=regtest' argument
4. Execute 'lnp-cli funds' command

**Other Links**
* Discuss about the prefix on Bitcoin Core ([here](https://github.com/bitcoin/bitcoin/issues/12314))

**Comment by dr-orlovsky** [comment]
Thank you! Will investigate and fix

**Comment by crisdut** [comment]
Hi @dr-orlovsky,

This issue is not a bug but a side effect of the bip32 strict encode. 

I explore this topic more [here](https://github.com/orgs/LNP-BP/discussions/128).
