### ISSUE TITLE
Panic starting node 'Unable to open key file'

### ISSUE THREAD

**Issue by grunch** [LNP-WG/lnp-node#56]
**Checklist**
- [x] Make sure you are using the latest code (`git checkout master && git pull origin`)
- [x] Compile only with rust nightly: `rustup default nightly && rustup update nightly && cargo test --all --all-features -v`
- [x] Try to do `cargo update`
- [x] Try to remove `target` directory

**Classify the bug**
Put `x` in the boxes below:
- [ ] Build issue
- [ ] Test failing
- [x] Runtime panic
- [ ] Incorrect results
- [ ] Unexpected/undocumented behaviour / 

**Describe the problem**
After try to start node it panics.

**To Reproduce**
```
lnpd -vvv
lnpd: lightning node management microservice
[2022-07-20T13:25:03Z DEBUG lnpd] MSG socket /home/grunch/.lnp_node/signet/msg
[2022-07-20T13:25:03Z DEBUG lnpd] CTL socket /home/grunch/.lnp_node/signet/ctl
[2022-07-20T13:25:03Z DEBUG lnpd] RPC socket 0.0.0.0:62962
[2022-07-20T13:25:03Z DEBUG lnpd] Starting runtime ...
thread 'main' panicked at 'Unable to open key file '/home/grunch/.lnp_node/signet/node.key';
please check that the file exists and the daemon has access rights to it', src/lnpd/daemons.rs:37:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
1. Linux pop-os 5.17.15-76051715-generic #202206141358~1655919116~22.04~1db9e34 SMP PREEMPT Wed Jun 22 19 x86_64 x86_64 x86_64 GNU/Linux
2. rustc 1.64.0-nightly (9a7b7d5e5 2022-07-19)

**Expected behavior**
The node should start.

**Comment by cooltexture** [comment]
You might need to run `$ lnpd init` before starting the daemon. I think this should be noted in the README, as it seems to be only mentioned in the `lnpd -h`.

**Comment by dr-orlovsky** [comment]
Instructions fixed in https://github.com/LNP-WG/lnp-node/pull/54
